# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Describe the function
#'
#' @param describe the params
#' 
#' @return describe the return 
AfsariCorcpp <- function(x, mydist) {
    .Call('_reva_AfsariCorcpp', PACKAGE = 'reva', x, mydist)
}

#' Describe the function
#'
#' @param describe the params
#' 
#' @return describe the return 
AfsariCorVarcpp <- function(mydist) {
    .Call('_reva_AfsariCorVarcpp', PACKAGE = 'reva', mydist)
}

#' Describe the function
#'
#' @param describe the params
#' 
#' @return describe the return 
AfsariCorVarcpp2 <- function(mydist) {
    .Call('_reva_AfsariCorVarcpp2', PACKAGE = 'reva', mydist)
}

