// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// AfsariCorcpp
double AfsariCorcpp(NumericVector x, NumericMatrix mydist);
RcppExport SEXP _REVA_AfsariCorcpp(SEXP xSEXP, SEXP mydistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mydist(mydistSEXP);
    rcpp_result_gen = Rcpp::wrap(AfsariCorcpp(x, mydist));
    return rcpp_result_gen;
END_RCPP
}
// AfsariCorVarcpp
double AfsariCorVarcpp(NumericMatrix mydist);
RcppExport SEXP _REVA_AfsariCorVarcpp(SEXP mydistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mydist(mydistSEXP);
    rcpp_result_gen = Rcpp::wrap(AfsariCorVarcpp(mydist));
    return rcpp_result_gen;
END_RCPP
}
// AfsariCorVarcpp2
NumericMatrix AfsariCorVarcpp2(NumericMatrix mydist);
RcppExport SEXP _REVA_AfsariCorVarcpp2(SEXP mydistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mydist(mydistSEXP);
    rcpp_result_gen = Rcpp::wrap(AfsariCorVarcpp2(mydist));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_REVA_AfsariCorcpp", (DL_FUNC) &_REVA_AfsariCorcpp, 2},
    {"_REVA_AfsariCorVarcpp", (DL_FUNC) &_REVA_AfsariCorVarcpp, 1},
    {"_REVA_AfsariCorVarcpp2", (DL_FUNC) &_REVA_AfsariCorVarcpp2, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_REVA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
